name: flutter_firebase_vote
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3
  uuid: ^2.0.4
  provider: ^4.1.2
  charts_flutter: ^0.12.0
  firebase_auth: ^0.16.1
  google_sign_in: ^4.5.1
  cloud_firestore: ^0.13.6
  loading: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:
  uses-material-design: true
